<?php

$first_number = 9;
$second_number = 4;

// === ADIÇÃO ===
$result = $first_number + $second_number;
echo "<h3>ADIÇÃO: $first_number + $second_number</h3>";
echo "<h3>Resultado: $result</h3>";

// === SUBTRAÇÃO ===
$result = $first_number - $second_number;
echo "<h3>SUBTRAÇÃO: $first_number - $second_number</h3>";
echo "<h3>Resultado: $result</h3>";

// === MULTIPLICAÇÃO ===
$result = $first_number * $second_number;
echo "<h3>MULTIPLICAÇÃO: $first_number * $second_number</h3>";
echo "<h3>Resultado: $result</h3>";

// === DIVISÃO ===
$result = $first_number / $second_number;
echo "<h3>DIVISÃO: $first_number / $second_number</h3>";
echo "<h3>Resultado: $result</h3>";

// === EXPONENCIAÇÃO ===
$result = $first_number ** $second_number;
echo "<h3>EXPONENCIAÇÃO: $first_number ** $second_number</h3>";
echo "<h3>Resultado: $result</h3>";

// === MÓDULO/RESTO DE ===
$result = $first_number % $second_number;
echo "<h3>MÓDULO/RESTO DE: $first_number % $second_number</h3>";
echo "<h3>Resultado: $result</h3>";

?>